# Generated by Django 5.0.2 on 2024-06-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maas', models.CharField(max_length=10)),
                ('Brans', models.CharField(max_length=50)),
                ('adsoyad', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=11)),
            ],
        ),
    ]
