# Generated by Django 5.0.2 on 2024-06-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogretmen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Teacher',
        ),
    ]
