# Generated by Django 5.0.2 on 2024-06-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogretmen', '0002_rename_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Brans',
            new_name='brans',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Maas',
            new_name='maas',
        ),
    ]
